from pathlib import Path
import hashlib, re, sys
R=Path(__file__).resolve().parents[1]
rd=lambda p:(R/p).read_text(encoding='utf-8',errors='ignore')
ex=lambda p:(R/p).is_file()
pf={p.relative_to(R).as_posix():p.read_text(encoding='utf-8',errors='ignore') for p in (R/'doctors-directory').rglob('*') if p.is_file()}
pt='\n'.join(pf.values())
rt='\n'.join(p.read_text(encoding='utf-8',errors='ignore') for p in R.rglob('*') if p.is_file() and '.git' not in p.parts and p.suffix.lower() in {'.php','.js','.css','.txt','.md','.yml','.yaml','.sh','.py'})
d=rd('doctors-directory/includes/class-sdd-directory.php'); h=rd('doctors-directory/includes/class-sdd-helpers.php')
p=rd('doctors-directory/includes/class-sdd-plugin.php'); a=rd('doctors-directory/includes/class-sdd-activator.php')
pr=rd('doctors-directory/includes/class-sdd-privacy.php'); se=rd('doctors-directory/includes/class-sdd-seo.php')
ha=rd('doctors-directory/includes/class-ddd-review-hardening.php'); xc=rd('doctors-directory/includes/class-ddd-cross-file-contracts.php'); u=rd('doctors-directory/uninstall.php')
f='\n'.join(rd(x) for x in ['doctors-directory/includes/class-ddd-future-query.php','doctors-directory/includes/class-ddd-future-discovery.php','doctors-directory/includes/class-ddd-future-preferences.php','doctors-directory/includes/class-ddd-future-mutation-guard.php','doctors-directory/includes/class-ddd-future-ui.php']); fjs=rd('doctors-directory/assets/js/future-discovery.js'); fcss=rd('doctors-directory/assets/css/future-discovery.css')
css=rd('doctors-directory/assets/css/directory.css'); m=rd('MANIFEST.md')
wb=rd('.github/workflows/file-07-quality-gates.yml'); wf=rd('.github/workflows/final-quality-gates.yml')
C=[]
def add(n,v): C.append((n,bool(v)))
add('Release identity 1.2.2',all(x in rd(y) for x,y in [('Version: 1.2.2','doctors-directory/doctors-directory.php'),('Stable tag: 1.2.2','doctors-directory/readme.txt'),('VERSION=1.2.2','tests/build-release.sh')]))
listed=[]
add('Exact-source CI integrity', 'git rev-parse HEAD' in wf and 'git diff --exit-code' in wf)
add('No obsolete pre-1.2.2 CI package path','1.2.1.zip' not in wb and '1.2.2' in wb)
core=['unit-helpers.php','source-contracts.py','central-plan-ranking.py','central-plan-adversarial.py','future-discovery-24.py','static-audit.sh','review-40.py','test-pagination.py','test-contrast.py']
add('Workflow core-gate parity',all(x in wb and x in wf for x in core))
add('Final workflow exact-source integrity','git rev-parse HEAD' in wf and 'git diff --exit-code' in wf)
add('Manifest covers future/review/release evidence',all(x in m for x in ['class-ddd-future-discovery.php','class-ddd-future-mutation-guard.php','class-ddd-cross-file-contracts.php','future-discovery.js','future-discovery.css','tests/future-discovery-24.py','docs/FUTURE-DISCOVERY-24-ENHANCEMENTS.md','.github/workflows/final-quality-gates.yml']))
add('Canonical release checksum generated from deterministic build','sha256sum build/07-doctors-directory-and-discovery-1.2.2.zip' in wf and 'cmp /tmp/build-a.zip' in wf)
add('Maintained checkout action','actions/checkout@v5' in wb and 'actions/checkout@v5' in wf)
req=['doctors-directory/doctors-directory.php','doctors-directory/includes/class-sdd-helpers.php','doctors-directory/includes/class-sdd-activator.php','doctors-directory/includes/class-sdd-directory.php','doctors-directory/includes/class-sdd-profile.php','doctors-directory/includes/class-sdd-admin.php','doctors-directory/includes/class-sdd-privacy.php','doctors-directory/includes/class-sdd-seo.php','doctors-directory/includes/class-sdd-plugin.php','doctors-directory/includes/class-ddd-review-hardening.php','doctors-directory/includes/class-ddd-central-ranking.php','doctors-directory/includes/class-ddd-ranking-ui.php','doctors-directory/includes/class-ddd-ranking-appeal.php','doctors-directory/includes/class-ddd-future-query.php','doctors-directory/includes/class-ddd-future-discovery.php','doctors-directory/includes/class-ddd-future-preferences.php','doctors-directory/includes/class-ddd-future-mutation-guard.php','doctors-directory/includes/class-ddd-future-ui.php','doctors-directory/uninstall.php']
add('Canonical runtime inventory',all(ex(x) for x in req))
add('Namespace/text-domain/package alignment',"define( 'DDD_VERSION'" in pt and 'doctors-directory-discovery' in pt and 'TOP=doctors-directory-and-discovery' in rd('tests/build-release.sh'))
add('No secret artifacts/literals',not any(x.suffix.lower() in {'.pem','.key','.p12','.env'} for x in R.rglob('*') if x.is_file()) and not re.search(r"(?i)(password|secret|api[_-]?key|access[_-]?token)\s*[:=]\s*['\"][^'\"]{16,}['\"]",rt))
add('PHP direct-access guards',all(("defined( 'ABSPATH' ) || exit;" in pf[x] or 'WP_UNINSTALL_PLUGIN' in pf[x]) for x in pf if x.endswith('.php')))
add('No destructive SQL/default uninstall',not re.search(r'\$wpdb->replace|\bREPLACE\s+INTO\b',pt,re.I) and 'DROP TABLE' not in u and 'wp_delete_post' not in u)
add('Transactional schema/indexes',"$engine = ' ENGINE=InnoDB '" in a and all(x in a for x in ['UNIQUE KEY public_id','UNIQUE KEY event_id','UNIQUE KEY idempotency_key']))
add('Tokenized activation/repair lock',all(x in a for x in ['LOCK_OPTION','expires','hash_equals','option_value=%s','finally']))
add('Bounded resumable migration',all(x in a for x in ['LEGACY_CURSOR_OPTION','LEGACY_BATCH','migrate_legacy_batch','ddd_continue_legacy_migration']))
add('Managed page lifecycle','PAGE_MAP_OPTION' in a and 'wp_insert_post' in a and 'wp_update_post' in a)
add('Mandatory owner fail-closed',all(x in h for x in ['mandatory_contract_missing','identity_contract_unavailable','profile_contract_unavailable','verification_contract_unavailable']))
add('Explicit eligibility and canonical owner states',all(x in h for x in ['account_active','risk_blocked','age_eligible','guardian_valid','verified','discoverable','public_destination_missing']) and all(x in xc for x in ['smc_membership_assertions','GDO_Integration_Contracts::projection','authorization_rechecked','appeal_review','erasure_pending','invalid_application']) and not any(x in h+xc for x in ['_smc_membership_status','_smc_suspension_status','_gdo_verification_status','_spd_verification_status']))
add('Founder separation/revalidation','founder_separate' in h and 'DDD_Contracts::founder' in pt and 'founder_claim' in ha and 'institutional' in ha)
add('Featured governance',all(x in d for x in ['feature_label','feature_start','feature_end','feature_audit','version_conflict','automatic_expiry']))
add('Stable signed cursor and required facets','cursor_decode' in h and 'cursor_encode' in h and 'filter_hash' in h and 'hash_hmac' in h and 'hash_equals' in h and 'DEFAULT_LIMIT' in d and all(x in pt for x in ['country','city','specialty','language','qualification','min_experience','mode','accepting','currency','fee_min','fee_max']))
add('Taxonomy/transliteration','taxonomy_upsert' in d and 'aliases_json' in d and 'normalize_token' in h and 'DoctorDirectoryTaxonomyChanged.v1' in d)
add('File03 canonical public UUID and same-origin destinations','uuid_from_user' not in h and 'canonical_public_id_missing' in h and 'same_origin_url' in h and 'hash_equals( $home_host, $target_host )' in h)
dto=re.search(r'public static function public_dto.*?\n\t}',d,re.S)
add('Public DTO minimization',dto and "'doctor_id' =>" not in dto.group(0) and "'avatar_id' =>" not in dto.group(0))
add('Saved/report integrity','save_reference' in d and 'DDD_Contracts::eligibility' in d and "'reporter:' . $reporter_id" in d and 'ddd_rate_limits' in a)
add('Atomic moderation/privacy lifecycle','report_transition_forbidden' in d and 'report_audit' in d and 'wp_privacy_personal_data_exporters' in pr and 'retention_hold=0' in ha)
add('Event reliability and live freshness',all(x in d for x in ['event_replay_mismatch','locked_by','locked_at',"status='processing' AND locked_at<",'attempts','dead']) and d.count('DDD_Contracts::eligibility')>=4 and 'get_live_status' in d)
add('REST permissions/SEO/accessibility',"current_user_can( 'ddd_run_reconciliation' )" in p and 'event_permission' in p and 'wp_sitemaps' in se and 'canonical' in se and all(x in css for x in ['focus-visible','min-height:44px','html[dir="rtl"]','prefers-reduced-motion']))
add('Future 24 governed IDs',all(f'F07-FUT-{i:02d}' in rd('docs/FUTURE-DISCOVERY-24-ENHANCEMENTS.md') for i in range(1,25)))
add('Future canonical-owner adapters',all(x in pt for x in ['sabri_file07_register_profile_provider','sabri_file08_public_clinic_projection_v1','sun_register_notification_producer','sun_ingest_domain_event','sabri_file25_search_provider']) and 'ddd_public_knowledge_footprint_v1' in f and 'sabri_file24_doctor_ranking_assurance_public_v1' in f and 'file24_ranking_assurance_blocked' in pt)
add('Future compare/guided/nearby/map',all(x in f for x in ['/future/compare','/future/guided','distance_km','map_points']) and 'navigator.geolocation' in fjs)
add('Future availability/time/country and fee truth',all(x in f for x in ['availability_days','local_availability','countries_served','serves_country']) and "!isset($fee['max'])" in f.replace(' ','') and "!isset($fee['min'])" in f.replace(' ',''))
add('Future private searches/shortlists/alerts',all(x in f for x in ['META_SEARCHES','META_SHORTLISTS','notify_saved_search_match','future_idempotency_key_required','future_mutation_rate_limited','X-DDD-Idempotent-Replay']) and "unset($f['lat'],$f['lng']" in f and 'Idempotency-Key' in fjs)
add('Future explanations/personal sort/transparency',all(x in f for x in ['why_this_doctor','personal_order_notice','not the official global merit rank','rest_transparency','File 26']))
add('Future professional/knowledge/accessibility',all(x in f for x in ['books_studied','teaching_experience','research_activity','knowledge_counts','communication_accessibility','clinic_accessibility']))
add('Future semantic/zero-result/integrity/demand',all(x in f for x in ['function interpret','zero_result_recovery','engagement_requires_manipulation_screen','OPTION_DEMAND']))
add('Future emergency/offline privacy',all(x in f for x in ['possible_emergency','directory_suppressed','offline_copy','stale_label_required','no free-text query','precise user location','must-revalidate']) and 'stale-if-error' not in f)
add('Future UI secure/accessibility', 'innerHTML = data' not in fjs and 'textContent' in fjs and all(x in fcss for x in ['focus-visible','min-height:44px','prefers-reduced-motion','html[dir="rtl"]']))
add('Safe Mode/operations/staging truth',all(x in p for x in ['DDD_SAFE_MODE_OPTION','system_check','set_safe_mode','redact']) and 'repair' in a.lower() and 'Hostinger' in rd('docs/STAGING-ACCEPTANCE.md') and 'rollback' in rd('docs/ROLLBACK.md').lower() and 'separate from Hostinger staging' in rd('README.md'))
bad=[(i+1,n) for i,(n,v) in enumerate(C) if not v]
for i,(n,v) in enumerate(C,1): print(f"{'PASS' if v else 'FAIL'} R{i:02d}: {n}")
print(f'TOTAL ROUNDS: {len(C)}\nPASS AFTER CORRECTION: {len(C)-len(bad)}\nFAIL AFTER CORRECTION: {len(bad)}')
if len(C)!=40: print('Exactly 40 rounds required.',file=sys.stderr); sys.exit(2)
if bad: print('FAILED ROUNDS: '+', '.join(f'R{i:02d}' for i,_ in bad),file=sys.stderr); sys.exit(1)
