from pathlib import Path
import re, sys
R=Path(__file__).resolve().parents[1]
D=R/'doctors-directory'
rd=lambda p:(R/p).read_text(encoding='utf-8',errors='ignore')
php_files=list(D.rglob('*.php'))
all_php='\n'.join(p.read_text(encoding='utf-8',errors='ignore') for p in php_files)
all_text='\n'.join(p.read_text(encoding='utf-8',errors='ignore') for p in D.rglob('*') if p.is_file())
h=rd('doctors-directory/includes/class-sdd-helpers.php')
a=rd('doctors-directory/includes/class-sdd-activator.php')
d=rd('doctors-directory/includes/class-sdd-directory.php')
plug=rd('doctors-directory/doctors-directory.php')
un=rd('doctors-directory/uninstall.php')
rank=rd('doctors-directory/includes/class-ddd-central-ranking.php')
appeal=rd('doctors-directory/includes/class-ddd-ranking-appeal.php')
fq=rd('doctors-directory/includes/class-ddd-future-query.php')
fd=rd('doctors-directory/includes/class-ddd-future-discovery.php')
fp=rd('doctors-directory/includes/class-ddd-future-preferences.php')
fu=rd('doctors-directory/includes/class-ddd-future-ui.php')
js=rd('doctors-directory/assets/js/future-discovery.js')
css=rd('doctors-directory/assets/css/future-discovery.css')
manifest=rd('doctors-directory/MANIFEST.sha256')
C=[]
def add(name,val): C.append((name,bool(val)))
add('Runtime release identity 1.2.0', "Version: 1.2.0" in plug and "DDD_VERSION', '1.2.0" in plug)
add('Database schema identity 1.1.0', "DDD_DB_VERSION', '1.1.0" in plug)
add('Contract identity 1.2.0', "DDD_CONTRACT_VERSION', '1.2.0" in plug)
add('Projection schema identity 2', "DDD_PROJECTION_SCHEMA', 2" in plug)
add('Canonical runtime inventory present', len(php_files)>=18 and all((D/p).exists() for p in ['assets/js/directory.js','assets/js/future-discovery.js','assets/css/directory.css','assets/css/future-discovery.css']))
add('PHP direct-access guards', all(("defined( 'ABSPATH' ) || exit;" in p.read_text(errors='ignore') or 'WP_UNINSTALL_PLUGIN' in p.read_text(errors='ignore')) for p in php_files))
add('No secret-key artifact extensions', not any(p.suffix.lower() in {'.pem','.key','.p12','.env'} for p in D.rglob('*') if p.is_file()))
add('No obvious hard-coded secret literals', not re.search(r"(?i)(password|secret|api[_-]?key|access[_-]?token)\s*[:=]\s*['\"][^'\"]{16,}['\"]",all_text))
add('No SQL REPLACE primitive', not re.search(r'\$wpdb->replace|\bREPLACE\s+INTO\b',all_php,re.I))
add('Default uninstall non-destructive', 'DROP TABLE' not in un and 'wp_delete_post' not in un)
add('Transactional InnoDB schema', "$engine = ' ENGINE=InnoDB '" in a and a.count('{$engine}{$charset}')>=8)
add('Uniqueness/idempotency indexes', all(x in a for x in ['UNIQUE KEY public_id','UNIQUE KEY event_id','UNIQUE KEY idempotency_key']))
add('Tokenized activation lock', all(x in a for x in ['LOCK_OPTION','hash_equals','finally']))
add('Bounded resumable legacy migration', all(x in a for x in ['LEGACY_CURSOR_OPTION','LEGACY_BATCH','migrate_legacy_batch']))
add('Server-side same-origin destination gate', 'same_origin_url' in h and 'hash_equals( $home_host, $target_host )' in h)
add('Signed HMAC cursor', 'cursor_encode' in h and 'hash_hmac' in h and 'hash_equals' in h)
add('Cursor bound to exact filter hash', 'cursor_decode' in h and 'expected_filter_hash' in h and "'fh'" in h)
add('Persistent bounded rate limiting', 'ddd_rate_limits' in h and 'request_count<%d' in h)
add('IP address stored only as keyed hash for rate controls', 'current_ip_hash' in h and "hash_hmac( 'sha256', $ip" in h)
dto=re.search(r'public static function public_dto.*?\n\t}',d,re.S)
add('Public DTO excludes internal doctor/avatar IDs', dto and "'doctor_id' =>" not in dto.group(0) and "'avatar_id' =>" not in dto.group(0))
add('File 00 identity contract fails closed', 'identity_contract_unavailable' in h and "'account_active'    => false" in h)
add('File 03 profile contract fails closed', 'profile_contract_unavailable' in h and "'discoverable'      => false" in h)
add('File 09 verification contract fails closed', 'verification_contract_unavailable' in h and "'verified'          => false" in h)
add('File 08 clinic contract remains optional', 'optional-unavailable' in h and 'clinic_provider_available' in h)
add('Click-time owner eligibility recheck', d.count('DDD_Contracts::eligibility')>=4 and 'get_live_status' in d)
add('Founder kept separate from ordinary doctor lists', 'founder_separate' in h and 'institutional' in h)
add('Featured doctor governance is versioned/audited/expiring', all(x in d for x in ['feature_label','feature_audit','version_conflict','automatic_expiry']))
add('Paid/donor ranking advantage prohibited', all(x in rank for x in ['donation','payment','paid_promotion','founder_favoritism','purchased_engagement']))
add('File 26 owns official merit ranking contract', 'sabri_file26_doctor_ranking_v1' in rank and 'File 26 global-ranking read bridge' in rank)
add('Top 10/100/1000/All Verified tiers encoded', all(x in rank for x in ['top10','top100','top1000','all']))
add('Ranking monthly freshness enforced', 'monthly_version' in rank and 'MAX_SNAPSHOT_AGE' in rank)
add('Ranking bias audit required', 'bias_audit' in rank and 'status' in rank)
add('Ranking appeal constrained to own live eligible doctor', 'get_live_status(get_current_user_id())' in appeal and 'hash_equals' in appeal)
add('Ranking appeal nonce protected', 'check_admin_referer' in appeal and 'wp_nonce_field' in appeal)
add('Ranking appeal rate limited', "rate_limit('ranking-appeal'" in appeal)
add('File 24 ranking assurance reduced to public allowlist', 'public_assurance' in rank and 'public_report_url' in rank and "'summary'" in rank)
add('Discovery accepts POST for sensitive searches', "WP_REST_Server::CREATABLE" in fd and "'/future/discover'" in fd)
add('GET rejects free-text/precise-location/personal weights', 'future_sensitive_query_requires_post' in fd and 'get_sensitive_params' in fd)
add('Natural-language interpretation is POST-only', "'/future/interpret'" in fd and re.search(r"'/future/interpret'.*?WP_REST_Server::CREATABLE",fd,re.S))
add('Sensitive discovery responses are private no-store', 'private, no-store, max-age=0' in fd and 'no_store_response' in fd)
add('Precise Near-Me coordinates are not persisted in saved searches/demand', "'lat'" not in re.search(r'private static function record_demand.*?\n\t}',fd,re.S).group(0) and "'lat'" not in re.search(r'private static function persistent_search_filters.*?\n\t}',fp,re.S).group(0))
add('Browser geolocation is reduced before transport', "toFixed(3)" in js and 'toFixed(6)' not in js)
add('Typed country/city clears stale geolocation', "form.querySelector('[name=\"lat\"]').value = ''" in js and "form.querySelector('[name=\"lng\"]').value = ''" in js)
add('Saved-search free text is converted or rejected, never stored raw', 'saved_search_unstructured_query' in fp and "'q'" not in re.search(r'\$allowed = array\(.*?\);',fp,re.S).group(0))
add('Saved-search REST data is private no-store', 'private_response' in fp and 'private, no-store, max-age=0' in fp)
add('Saved-search API hides internal last-notified fingerprints', 'public_search_row' in fp and "'last_notified'" not in re.search(r'private static function public_search_row.*?\n\t}',fp,re.S).group(0))
add('Saved-search matcher enforces qualification', "$p['qualification']" in fq and "['qualification']" in fq)
add('Saved-search matcher enforces experience', "$p['min_experience']" in fq and "experience_years" in fq)
add('Saved-search matcher enforces fee/currency', "$p['fee_min']" in fq and "$p['fee_max']" in fq and "fee['currency']" in fq)
add('Shortlist supplied ID must be canonical 32-hex', "preg_match( '/^[a-f0-9]{32}$/', $id )" in fp)
add('Shortlist limit cannot be bypassed with invented ID', 'shortlist_not_found' in fp and 'count( $lists ) >= self::MAX_LISTS' in fp)
add('Shortlist doctor eligibility rechecked before save', 'get_by_public_id( $public_id )' in fp and 'shortlist_doctor_unavailable' in fp)
add('Saved-search alerts require File 19 provider presence', "has_action( 'sabri_file19_notification_event_v1' )" in fp and 'notification_provider_unavailable' in fp)
add('Saved-search worker has stale-safe concurrency lock', 'acquire_lock' in fp and 'LOCK_TTL' in fp and 'add_option' in fp and 'finally' in fp)
add('Saved-search fingerprint is not advanced when provider is absent', fp.index("has_action( 'sabri_file19_notification_event_v1' )") < fp.index("$seen[] = $fingerprint"))
add('Compare requires 2–4 eligible doctors', 'MAX_COMPARE=4' in fd and 'compare_count' in fd and 'get_by_public_id' in fd)
add('Compare renders canonical nested fee DTO', 'd.fee && d.fee.min' in js and 'd.fee_min' not in js)
add('Compare availability uses requester timezone', "timezone: (tz && tz.value)" in js and "'timezone' => array" in fd)
add('Personal fee preference uses canonical nested fee DTO', "is_array($d['fee']??null)" in fq and "fee['min']" in fq)
add('Normalized empty semantic needle cannot match everything', "if(''===$n)return false" in fq)
add('Map and list are both present', 'map_points' in fd and 'renderMap' in js and 'ddd-future__results' in css)
add('Map pins meet 44px touch target', re.search(r'\.ddd-future-pin\{[^}]*width:44px;height:44px;min-height:44px',css))
add('Compare selector meets 44px touch target', re.search(r'\.ddd-future-card__top input\{[^}]*width:44px;height:44px',css))
add('Form button container class matches CSS', 'ddd-future__buttons' in fu and '.ddd-future__buttons{' in css and '.ddd-future__actions{' not in css)
add('Client validates same-origin action links', 'safeSameOriginHref' in js and 'window.location.origin' in js)
add('JS smooth scroll honors reduced-motion preference', 'prefersReducedMotion()' in js and "behavior: prefersReducedMotion() ? 'auto' : 'smooth'" in js)
add('CSS disables animation/transition under reduced motion', '@media(prefers-reduced-motion:reduce)' in css and 'animation:none!important' in css)
add('Advanced discovery exposes signed-cursor continuation in UI', 'data-ddd-load-more' in fu and 'nextCursor' in js and 'p.cursor = nextCursor' in js)
add('Zero-result demand/recovery only occurs at terminal cursor', '$has_more' in fd and 'if ( ! $items && ! $has_more )' in fd and '( $items || $has_more ) ? array()' in fd)
add('Unmet-demand aggregation excludes raw query and coordinates', all(x in fd for x in ["'country'", "'city'", "'specialty'", "'language'", "'mode'"]) and 'no free-text query, IP, precise user location' in fd)
add('File 26 transparency policy fields are allowlisted', 'public_policy' in fd and 'appeal_url' in fd and 'explanation_url' in fd and "array_map( 'sanitize_key'" in fd)
add('File 24 transparency response is public-field minimized', 'public_assurance' in fd and "'public_report_url'" in fd and "'summary'" in fd)
add('Compare endpoint is rate limited', "public_rate_limit( 'future_compare'" in fd)
add('Interpret endpoint is rate limited', "public_rate_limit( 'future_interpret'" in fd)
add('Offline pack endpoint is rate limited', "public_rate_limit( 'future_offline_pack'" in fd)
add('Future UI never assigns untrusted response HTML', 'innerHTML = data' not in js and '.textContent =' in js)
add('JS-generated interface strings are wired to localization dictionary', 'function msg(key, fallback)' in js and "'messages'=>array(" in fu and "msg('specialty'" in js)
add('Emergency query diversion suppresses normal directory results', 'possible_emergency' in fq and 'directory_suppressed' in fq and 'safety_diversion' in fd)
add('Offline pack exposes only explicit public-safe field allowlist', 'array_intersect_key( $doctor' in fd and "'public_id', 'display_name', 'professional_title'" in fd and 'stale_label_required' in fd)
add('Admin health/repair surfaces remain capability-gated', "current_user_can( 'ddd_view_health' )" in rd('doctors-directory/includes/class-sdd-plugin.php') and "current_user_can( 'ddd_repair_directory' )" in rd('doctors-directory/includes/class-sdd-plugin.php'))

bad=[(i+1,n) for i,(n,v) in enumerate(C) if not v]
for i,(n,v) in enumerate(C,1): print(f"{'PASS' if v else 'FAIL'} R{i:02d}: {n}")
print(f'TOTAL ROUNDS: {len(C)}')
print(f'PASS AFTER CORRECTION: {len(C)-len(bad)}')
print(f'FAIL AFTER CORRECTION: {len(bad)}')
if len(C)!=80:
    print(f'Exactly 80 rounds required; got {len(C)}.',file=sys.stderr); sys.exit(2)
if bad:
    print('FAILED ROUNDS: '+', '.join(f'R{i:02d} {n}' for i,n in bad),file=sys.stderr); sys.exit(1)
