<?php
defined( 'ABSPATH' ) || exit;

final class DDD_Ranking_UI {
	private static $renderer = null;
	public static function register() {
		add_filter( 'do_shortcode_tag', array( __CLASS__, 'enhance' ), 40, 4 );
		add_action( 'wp_enqueue_scripts', array( __CLASS__, 'styles' ), 40 );
	}
	public static function styles() {
		wp_add_inline_style( 'ddd-directory', '.ddd-ranking-tier-nav{display:flex;flex-wrap:wrap;gap:.55rem;margin:1rem 0}.ddd-ranking-tier-nav a{min-height:44px;display:inline-flex;align-items:center;justify-content:center}.ddd-ranking-tier-nav a[aria-current="page"]{font-weight:700}.ddd-central-ranking-meta{border:1px solid currentColor;border-radius:12px;padding:1rem;margin:1rem 0}.ddd-central-ranking-meta p{margin:.35rem 0}.ddd-global-rank-badge{display:inline-flex;min-height:32px;align-items:center;font-weight:700;margin:0 0 .45rem}.ddd-central-tier-focused>section[aria-labelledby="ddd-featured-doctors"],.ddd-central-tier-focused>section[aria-labelledby="ddd-recently-verified-doctors"]{display:none}.ddd-ranking-appeal textarea{width:100%;min-height:110px}.ddd-ranking-degraded{border-left:4px solid currentColor;padding:.75rem 1rem}.ddd-ranking-policy-list{margin:.5rem 0 0;padding-inline-start:1.25rem}' );
	}
	public static function enhance( $output, $tag, $attr, $m ) {
		if ( ! in_array($tag,array('ddd_doctors_directory','sdd_doctors_directory'),true) || false===strpos($output,'data-ddd-directory') ) { return $output; }
		$tier=DDD_Central_Ranking::tier(); $snapshot=DDD_Central_Ranking::snapshot($tier,DDD_Central_Ranking::filters()); $ui=self::render($tier,$snapshot);
		$output=preg_replace('/class="ddd-shell"/','class="ddd-shell ddd-central-ranking-active'.('all'!==$tier?' ddd-central-tier-focused':'').'"',$output,1);
		/* Remove the legacy File-07-local ranked All/Search section from the rendered DOM. */
		$pos=false; foreach(array('<section class="ddd-section" aria-labelledby="ddd-all-doctors">','<section class="ddd-section" aria-labelledby="ddd-search-results">') as $marker){$p=strpos($output,$marker);if(false!==$p){$end=strpos($output,'</section>',$p);if(false!==$end){$end+=strlen('</section>');$output=substr($output,0,$p).substr($output,$end);$pos=$p;break;}}}
		if(false===$pos){$pos=strrpos($output,'</main>');} return false===$pos?$output.$ui:substr($output,0,$pos).$ui.substr($output,$pos);
	}
	private static function render( $tier, $snapshot ) {
		$title=array('top10'=>__('Top 10 Homeopathic Doctors',DDD_TEXT_DOMAIN),'top100'=>__('Top 100 Homeopathic Doctors',DDD_TEXT_DOMAIN),'top1000'=>__('Top 1000 Homeopathic Doctors',DDD_TEXT_DOMAIN),'all'=>__('All Verified Doctors',DDD_TEXT_DOMAIN)); ob_start(); ?>
		<section class="ddd-section ddd-central-ranking-section" aria-labelledby="ddd-global-ranking-tier"><div class="ddd-section-head"><div><h2 id="ddd-global-ranking-tier"><?php echo esc_html($title[$tier]); ?></h2><p><?php echo esc_html(is_wp_error($snapshot)?__('File 26 global ranking is unavailable; no synthetic rank is shown.',DDD_TEXT_DOMAIN):('file26'===$snapshot['source']?__('Global ranking is supplied by File 26; File 07 validates current public eligibility before rendering.',DDD_TEXT_DOMAIN):__('All Verified Doctors is using neutral alphabetical order; no merit rank is asserted.',DDD_TEXT_DOMAIN))); ?></p></div></div>
		<?php echo self::nav($tier); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
		<?php if(is_wp_error($snapshot)): ?><div class="ddd-ranking-degraded" role="status"><strong><?php esc_html_e('Ranking temporarily unavailable',DDD_TEXT_DOMAIN); ?></strong><p><?php echo esc_html($snapshot->get_error_message()); ?></p><p><?php esc_html_e('Use All Verified Doctors to browse safely without an invented rank.',DDD_TEXT_DOMAIN); ?></p></div>
		<?php else: echo self::meta($snapshot); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?><div class="ddd-grid"><?php $items=DDD_Central_Ranking::public_items($snapshot); if($items): foreach($items as $doctor): ?><div class="ddd-ranked-card"><?php if(!empty($doctor['global_rank'])):?><span class="ddd-global-rank-badge"><?php echo esc_html(sprintf(__('Global rank #%d',DDD_TEXT_DOMAIN),$doctor['global_rank'])); ?></span><?php endif; echo self::renderer()->card($doctor); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></div><?php endforeach; else:?><div class="ddd-empty" role="status"><h3><?php esc_html_e('No eligible doctors matched this view',DDD_TEXT_DOMAIN); ?></h3><p><?php esc_html_e('Try broader filters or another tier. No synthetic result is created.',DDD_TEXT_DOMAIN); ?></p></div><?php endif;?></div>
		<?php if(!empty($snapshot['next_cursor'])):?><nav class="ddd-pagination" aria-label="<?php esc_attr_e('Global ranking pagination',DDD_TEXT_DOMAIN); ?>"><a class="ddd-button ddd-button-light" href="<?php echo esc_url(self::url($tier,$snapshot['next_cursor'])); ?>"><?php esc_html_e('Next results',DDD_TEXT_DOMAIN); ?></a></nav><?php endif; if('file26'===$snapshot['source']){echo DDD_Ranking_Appeal::form($snapshot,$tier);} // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
		endif; ?>
		</section><?php return ob_get_clean();
	}
	private static function renderer(){if(!self::$renderer){self::$renderer=new DDD_Directory();}return self::$renderer;}
	private static function nav($current){$l=array('top10'=>__('Top 10',DDD_TEXT_DOMAIN),'top100'=>__('Top 100',DDD_TEXT_DOMAIN),'top1000'=>__('Top 1000',DDD_TEXT_DOMAIN),'all'=>__('All Verified Doctors',DDD_TEXT_DOMAIN));$o='<nav class="ddd-ranking-tier-nav" aria-label="'.esc_attr__('Global doctor ranking tiers',DDD_TEXT_DOMAIN).'">';foreach($l as $t=>$x){$o.='<a class="ddd-button ddd-button-light" '.($t===$current?'aria-current="page" ':'').'href="'.esc_url(self::url($t)).'">'.esc_html($x).'</a>';}return $o.'</nav>';}
	private static function url($tier,$cursor=''){$u=remove_query_arg(array('doctor_rank_cursor','doctor_cursor'));$u=add_query_arg('doctor_tier',$tier,$u);return $cursor?add_query_arg('doctor_rank_cursor',$cursor,$u):$u;}
	private static function meta($s){if('neutral'===$s['source']){return '<div class="ddd-central-ranking-meta" role="status"><p><strong>'.esc_html__('Neutral fallback order',DDD_TEXT_DOMAIN).'</strong></p><p>'.esc_html__('Alphabetical ordering is not a global rank; Top 10/100/1000 are never fabricated.',DDD_TEXT_DOMAIN).'</p></div>';}$a=isset($s['assurance']['status'])?sanitize_key((string)$s['assurance']['status']):'unavailable';$at='pass'===$a?__('Independent File 24 fairness assurance: passed.',DDD_TEXT_DOMAIN):__('Independent File 24 assurance is unavailable; File 26 bias-audit attestation is not overstated as independent assurance.',DDD_TEXT_DOMAIN);return '<div class="ddd-central-ranking-meta"><p><strong>'.esc_html__('Ranking policy',DDD_TEXT_DOMAIN).':</strong> '.esc_html($s['policy_version']).'</p><p><strong>'.esc_html__('Monthly version',DDD_TEXT_DOMAIN).':</strong> '.esc_html($s['monthly_version']).' · <strong>'.esc_html__('Generated',DDD_TEXT_DOMAIN).':</strong> '.esc_html($s['generated_at']).' UTC</p><p><strong>'.esc_html__('Bias audit',DDD_TEXT_DOMAIN).':</strong> '.esc_html__('Pass — donation, payment, paid promotion, Founder favoritism and purchased engagement cannot create a ranking advantage.',DDD_TEXT_DOMAIN).'</p><p>'.esc_html($at).'</p><ul class="ddd-ranking-policy-list"><li>'.esc_html__('Tiers are nested: Top 10 ⊂ Top 100 ⊂ Top 1000 ⊂ All Verified.',DDD_TEXT_DOMAIN).'</li><li>'.esc_html__('Why-this-rank explanations come from File 26; File 07 rechecks current public eligibility.',DDD_TEXT_DOMAIN).'</li></ul></div>';}
}
add_action('plugins_loaded',array('DDD_Ranking_UI','register'),32);
