<?php
defined( 'ABSPATH' ) || exit;

/** Private saved discovery preferences and File-19 alert handoff. */
final class DDD_Future_Preferences {
	const META_SEARCHES='ddd_saved_searches_v1'; const META_SHORTLISTS='ddd_shortlists_v1';
	const MAX_SEARCHES=20; const MAX_LISTS=10; const MAX_SHORTLIST_ITEMS=20; const BATCH=100;
	public static function register(){add_action('rest_api_init',array(__CLASS__,'routes'));add_action('ddd_projection_rebuilt',array(__CLASS__,'queue'),20,2);add_action('ddd_future_availability_changed',array(__CLASS__,'queue'),20,2);add_action('ddd_future_match_saved_searches',array(__CLASS__,'process'),10,2);add_filter('wp_privacy_personal_data_exporters',array(__CLASS__,'exporters'));add_filter('wp_privacy_personal_data_erasers',array(__CLASS__,'erasers'));}
	public static function routes(){
		$ns=DDD_Future_Discovery::REST_NS;$login='is_user_logged_in';
		register_rest_route($ns,'/future/saved-searches',array(array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'get_searches'),'permission_callback'=>$login),array('methods'=>WP_REST_Server::CREATABLE,'callback'=>array(__CLASS__,'save_search'),'permission_callback'=>$login)));
		register_rest_route($ns,'/future/saved-searches/(?P<id>[a-f0-9]{32})',array('methods'=>WP_REST_Server::DELETABLE,'callback'=>array(__CLASS__,'delete_search'),'permission_callback'=>$login));
		register_rest_route($ns,'/future/shortlists',array(array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'get_lists'),'permission_callback'=>$login),array('methods'=>WP_REST_Server::CREATABLE,'callback'=>array(__CLASS__,'save_list'),'permission_callback'=>$login)));
		register_rest_route($ns,'/future/shortlists/(?P<id>[a-f0-9]{32})',array('methods'=>WP_REST_Server::DELETABLE,'callback'=>array(__CLASS__,'delete_list'),'permission_callback'=>$login));
	}
	private static function searches($u){$v=get_user_meta(absint($u),self::META_SEARCHES,true);return is_array($v)?array_slice($v,0,self::MAX_SEARCHES):array();}
	private static function lists($u){$v=get_user_meta(absint($u),self::META_SHORTLISTS,true);return is_array($v)?array_slice($v,0,self::MAX_LISTS):array();}
	public static function get_searches(){return rest_ensure_response(array('items'=>self::searches(get_current_user_id())));}
	public static function save_search(WP_REST_Request $r){if(DDD_Observability::safe_mode())return DDD_Helpers::safe_error('safe_mode',__('Saved searches are temporarily unavailable.',DDD_TEXT_DOMAIN),503);$u=get_current_user_id();$items=self::searches($u);if(count($items)>=self::MAX_SEARCHES)return DDD_Helpers::safe_error('saved_search_limit',__('Saved-search limit reached.',DDD_TEXT_DOMAIN),409);$raw=(array)($r->get_json_params()?:$r->get_params());$f=DDD_Future_Discovery::sanitize_params((array)($raw['filters']??array()));unset($f['lat'],$f['lng'],$f['weights'],$f['cursor']);$id=md5(wp_generate_uuid4().'|'.$u.'|'.microtime(true));$items[]=array('id'=>$id,'label'=>sanitize_text_field((string)($raw['label']??__('Saved doctor search',DDD_TEXT_DOMAIN))),'filters'=>$f,'created_at'=>gmdate('c'),'last_notified'=>array());update_user_meta($u,self::META_SEARCHES,$items);return new WP_REST_Response(array('saved'=>true,'id'=>$id),201);}
	public static function delete_search(WP_REST_Request $r){$u=get_current_user_id();$id=sanitize_key((string)$r['id']);update_user_meta($u,self::META_SEARCHES,array_values(array_filter(self::searches($u),static function($x)use($id){return($x['id']??'')!==$id;})));return rest_ensure_response(array('deleted'=>true));}
	public static function get_lists(){return rest_ensure_response(array('items'=>self::lists(get_current_user_id())));}
	public static function save_list(WP_REST_Request $r){if(DDD_Observability::safe_mode())return DDD_Helpers::safe_error('safe_mode',__('Shortlists are temporarily unavailable.',DDD_TEXT_DOMAIN),503);$u=get_current_user_id();$raw=(array)($r->get_json_params()?:$r->get_params());$id=sanitize_key((string)($raw['id']??''));$lists=self::lists($u);if(!$id&&count($lists)>=self::MAX_LISTS)return DDD_Helpers::safe_error('shortlist_limit',__('Shortlist limit reached.',DDD_TEXT_DOMAIN),409);$ids=array_values(array_unique(array_filter(array_map('sanitize_text_field',(array)($raw['public_ids']??array())),array('DDD_Helpers','valid_public_id'))));$ids=array_slice($ids,0,self::MAX_SHORTLIST_ITEMS);foreach($ids as $pid)if(!DDD_Repository::get_by_public_id($pid))return DDD_Helpers::safe_error('shortlist_doctor_unavailable',__('A selected doctor is no longer publicly eligible.',DDD_TEXT_DOMAIN),409);$row=array('id'=>$id?:md5(wp_generate_uuid4().'|'.$u),'label'=>sanitize_text_field((string)($raw['label']??__('My shortlist',DDD_TEXT_DOMAIN))),'public_ids'=>$ids,'updated_at'=>gmdate('c'));$found=false;foreach($lists as $k=>$x)if(($x['id']??'')===$row['id']){$lists[$k]=$row;$found=true;break;}if(!$found)$lists[]=$row;update_user_meta($u,self::META_SHORTLISTS,$lists);return rest_ensure_response(array('saved'=>true,'id'=>$row['id']));}
	public static function delete_list(WP_REST_Request $r){$u=get_current_user_id();$id=sanitize_key((string)$r['id']);update_user_meta($u,self::META_SHORTLISTS,array_values(array_filter(self::lists($u),static function($x)use($id){return($x['id']??'')!==$id;})));return rest_ensure_response(array('deleted'=>true));}
	public static function queue($doctor_id,$data=array()){$id=absint($doctor_id);if(!$id)return;if(!wp_next_scheduled('ddd_future_match_saved_searches',array($id,0)))wp_schedule_single_event(time()+5,'ddd_future_match_saved_searches',array($id,0));}
	public static function process($doctor_id,$cursor=0){global$wpdb;$id=absint($doctor_id);$cursor=absint($cursor);if(!$id)return;$status=DDD_Repository::get_status($id);if(empty($status['eligible'])||empty($status['public_id']))return;$doctor=DDD_Repository::get_by_public_id($status['public_id']);if(!$doctor)return;$rows=$wpdb->get_results($wpdb->prepare("SELECT umeta_id,user_id,meta_value FROM {$wpdb->usermeta} WHERE meta_key=%s AND umeta_id>%d ORDER BY umeta_id ASC LIMIT %d",self::META_SEARCHES,$cursor,self::BATCH),ARRAY_A);$last=$cursor;foreach((array)$rows as $row){$last=absint($row['umeta_id']);$searches=maybe_unserialize($row['meta_value']);if(!is_array($searches))continue;$changed=false;foreach($searches as&$search){$p=DDD_Future_Discovery::sanitize_params((array)($search['filters']??array()));$d=DDD_Future_Discovery::enrich_doctor($doctor,$p);if(!DDD_Future_Discovery::matches_saved_search($d,$p))continue;$seen=is_array($search['last_notified']??null)?$search['last_notified']:array();$fp=substr(hash('sha256',$doctor['public_id'].'|'.($doctor['verified_at']??'').'|'.($d['freshness']['availability']??'')),0,24);if(in_array($fp,$seen,true))continue;do_action('sabri_file19_notification_event_v1',array('event'=>'DoctorSavedSearchMatched.v1','recipient_user_id'=>absint($row['user_id']),'category'=>'doctor_discovery','priority'=>'normal','object_public_id'=>$doctor['public_id'],'search_id'=>sanitize_key((string)($search['id']??'')),'deep_link'=>home_url('/doctors/')));$seen[]=$fp;$search['last_notified']=array_slice(array_values(array_unique($seen)),-20);$changed=true;}unset($search);if($changed)update_user_meta(absint($row['user_id']),self::META_SEARCHES,$searches);}if(count($rows)===self::BATCH)wp_schedule_single_event(time()+5,'ddd_future_match_saved_searches',array($id,$last));}
	public static function exporters($x){$x['ddd-future-discovery']=array('exporter_friendly_name'=>__('Doctor discovery preferences',DDD_TEXT_DOMAIN),'callback'=>array(__CLASS__,'export'));return$x;} public static function erasers($x){$x['ddd-future-discovery']=array('eraser_friendly_name'=>__('Doctor discovery preferences',DDD_TEXT_DOMAIN),'callback'=>array(__CLASS__,'erase'));return$x;}
	public static function export($email,$page=1){$u=get_user_by('email',$email);if(!$u)return array('data'=>array(),'done'=>true);$s=self::searches($u->ID);$l=self::lists($u->ID);$data=array();if($s||$l)$data[]=array('group_id'=>'ddd-future-discovery','group_label'=>__('Doctor discovery preferences',DDD_TEXT_DOMAIN),'item_id'=>'ddd-future-'.$u->ID,'data'=>array(array('name'=>__('Saved searches',DDD_TEXT_DOMAIN),'value'=>wp_json_encode($s)),array('name'=>__('Shortlists',DDD_TEXT_DOMAIN),'value'=>wp_json_encode($l))));return array('data'=>$data,'done'=>true);}
	public static function erase($email,$page=1){$u=get_user_by('email',$email);if(!$u)return array('items_removed'=>false,'items_retained'=>false,'messages'=>array(),'done'=>true);$removed=delete_user_meta($u->ID,self::META_SEARCHES);$removed=delete_user_meta($u->ID,self::META_SHORTLISTS)||$removed;return array('items_removed'=>(bool)$removed,'items_retained'=>false,'messages'=>array(),'done'=>true);}
}
