<?php
defined( 'ABSPATH' ) || exit;
/** F07-FUT-01..24 route/orchestration facade; canonical truths remain with owner files. */
final class DDD_Future_Discovery {
	const REST_NS='doctors-directory-discovery/v1'; const OPTION_DEMAND='ddd_unmet_demand_v1'; const MAX_COMPARE=4; const CONTRACT_VERSION='1.0';
	public static function register(){add_action('rest_api_init',array(__CLASS__,'routes'));add_filter('ddd_file07_discovery_integrity_v1',array(__CLASS__,'integrity_contract'),10,2);DDD_Future_Preferences::register();DDD_Future_UI::register();}
	public static function routes(){$pub='__return_true';register_rest_route(self::REST_NS,'/future/discover',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'rest_discover'),'permission_callback'=>$pub,'args'=>DDD_Future_Query::args()));register_rest_route(self::REST_NS,'/future/guided',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'rest_guided'),'permission_callback'=>$pub,'args'=>DDD_Future_Query::args()));register_rest_route(self::REST_NS,'/future/compare',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'rest_compare'),'permission_callback'=>$pub,'args'=>array('ids'=>array('required'=>true,'sanitize_callback'=>'sanitize_text_field'))));register_rest_route(self::REST_NS,'/future/interpret',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'rest_interpret'),'permission_callback'=>$pub,'args'=>array('q'=>array('required'=>true,'sanitize_callback'=>'sanitize_text_field'))));register_rest_route(self::REST_NS,'/future/transparency',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'rest_transparency'),'permission_callback'=>$pub));register_rest_route(self::REST_NS,'/future/offline-pack',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'rest_offline_pack'),'permission_callback'=>$pub,'args'=>array('country'=>array('sanitize_callback'=>'sanitize_text_field'),'city'=>array('sanitize_callback'=>'sanitize_text_field'),'language'=>array('sanitize_callback'=>'sanitize_text_field'))));register_rest_route(self::REST_NS,'/future/demand',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'rest_demand'),'permission_callback'=>static function(){return current_user_can('ddd_view_health');}));}
	public static function sanitize_params($r){return DDD_Future_Query::sanitize($r);} public static function enrich_doctor($d,$p){return DDD_Future_Query::enrich($d,$p);} public static function matches_saved_search($d,$p){return DDD_Future_Query::saved_match($d,$p);}
	public static function rest_discover(WP_REST_Request$r){if(!DDD_Helpers::rate_limit('future_discover',DDD_Helpers::current_ip_hash(),90,MINUTE_IN_SECONDS))return DDD_Helpers::safe_error('future_search_rate_limited',__('Discovery rate limit exceeded.',DDD_TEXT_DOMAIN),429);$p=DDD_Future_Query::sanitize($r->get_params());$i=DDD_Future_Query::interpret($p['q']);if(!empty($i['safety_diversion']))return rest_ensure_response(array('items'=>array(),'safety_diversion'=>$i['safety_diversion'],'query_interpretation'=>$i));$p=DDD_Future_Query::merge($p,$i);$base=DDD_Repository::search(DDD_Future_Query::repository($p));if(is_wp_error($base))return$base;$items=array();foreach((array)($base['items']??array())as$d){$d=DDD_Future_Query::enrich($d,$p);if(DDD_Future_Query::matches($d,$p)){$d['why_this_doctor']=DDD_Future_Query::why($d,$p);$items[]=$d;}}if($p['lat']!==null&&$p['lng']!==null)usort($items,static function($a,$b){return($a['distance_km']??PHP_FLOAT_MAX)<=>($b['distance_km']??PHP_FLOAT_MAX);});$personal=false;$items=DDD_Future_Query::personal($items,$p['weights'],$p,$personal);if(!$items)self::record_demand($p);$out=array('items'=>array_values($items),'next_cursor'=>sanitize_text_field((string)($base['next_cursor']??'')),'personal_order'=>$personal,'personal_order_notice'=>$personal?__('This order reflects your own display preferences; it is not the official global merit rank.',DDD_TEXT_DOMAIN):'','query_interpretation'=>$i,'recovery'=>$items?array():DDD_Future_Query::zero_result_recovery($p),'map_points'=>DDD_Future_Query::map_points($items),'generated_at'=>gmdate('c'),'contract_version'=>self::CONTRACT_VERSION);$res=rest_ensure_response($out);$res->header('Cache-Control',($p['lat']!==null||$personal)?'private, no-store, max-age=0':'public, max-age=45, stale-while-revalidate=90');return$res;}
	public static function rest_guided(WP_REST_Request$r){$p=$r->get_params();$p['accepting']=true;$x=new WP_REST_Request('GET','/');foreach($p as$k=>$v)$x->set_param($k,$v);return self::rest_discover($x);} public static function rest_interpret(WP_REST_Request$r){return rest_ensure_response(DDD_Future_Query::interpret((string)$r['q']));}
	public static function rest_compare(WP_REST_Request$r){$ids=array_values(array_unique(array_filter(array_map('trim',explode(',',(string)$r['ids'])))));if(count($ids)<2||count($ids)>self::MAX_COMPARE)return DDD_Helpers::safe_error('compare_count',__('Compare between two and four doctors.',DDD_TEXT_DOMAIN),400);$p=DDD_Future_Query::sanitize(array('timezone'=>'UTC'));$items=array();foreach($ids as$id)if(DDD_Helpers::valid_public_id($id)){ $d=DDD_Repository::get_by_public_id($id);if($d)$items[]=DDD_Future_Query::enrich($d,$p);}if(count($items)<2)return DDD_Helpers::safe_error('compare_unavailable',__('At least two eligible doctors are required for comparison.',DDD_TEXT_DOMAIN),404);return rest_ensure_response(array('items'=>$items,'notice'=>__('This is a factual comparison, not a platform recommendation or treatment guarantee.',DDD_TEXT_DOMAIN)));}
	private static function record_demand($p){$f=array('country'=>$p['country'],'city'=>$p['city'],'specialty'=>$p['specialty'],'language'=>$p['language'],'mode'=>$p['mode']);if(!array_filter($f))return;$key=substr(hash('sha256',wp_json_encode($f)),0,20);$all=get_option(self::OPTION_DEMAND,array());if(!is_array($all))$all=array();$row=is_array($all[$key]??null)?$all[$key]:array('filters'=>$f,'count'=>0,'first_seen'=>gmdate('c'));$row['count']=absint($row['count']??0)+1;$row['last_seen']=gmdate('c');$all[$key]=$row;uasort($all,static function($a,$b){return absint($b['count']??0)<=>absint($a['count']??0);});update_option(self::OPTION_DEMAND,array_slice($all,0,200,true),false);}
	public static function rest_demand(){return rest_ensure_response(array('items'=>array_values((array)get_option(self::OPTION_DEMAND,array())),'privacy'=>'Aggregated filters only; no free-text query, IP, precise user location or patient data.'));}
	public static function rest_transparency(){$policy=apply_filters('sabri_file26_ranking_policy_public_v1',null,array('consumer'=>'file07','contract_version'=>self::CONTRACT_VERSION));$policy=is_array($policy)?array_intersect_key($policy,array_flip(array('policy_version','monthly_version','generated_at','signals','appeal_url','explanation_url'))):array();$assurance=apply_filters('sabri_file24_doctor_ranking_assurance_public_v1',null,array('consumer'=>'file07'));if(!is_array($assurance))$assurance=array('status'=>'unavailable');return rest_ensure_response(array('owner'=>'File 26','consumer'=>'File 07','official_tiers'=>array('Top 10','Top 100','Top 1000','All Verified Doctors'),'prohibited_signals'=>array('donation','payment','paid_promotion','founder_favoritism','purchased_engagement'),'personal_sort_is_not_global_rank'=>true,'policy'=>$policy,'independent_assurance'=>$assurance));}
	public static function integrity_contract($result,$request){$s=array_map('sanitize_key',(array)($request['signals']??array()));$bad=array('donation','payment','paid_promotion','founder_favoritism','purchased_engagement');$blocked=array_values(array_intersect($s,$bad));return array('contract_version'=>self::CONTRACT_VERSION,'allow_as_merit_signal'=>empty($blocked),'blocked_signals'=>$blocked,'engagement_requires_manipulation_screen'=>true,'source'=>'file07-discovery-integrity');}
	public static function rest_offline_pack(WP_REST_Request$r){$p=DDD_Future_Query::sanitize(array('country'=>$r['country'],'city'=>$r['city'],'language'=>$r['language'],'limit'=>DDD_Future_Query::MAX_RESULTS));$b=DDD_Repository::search(DDD_Future_Query::repository($p));if(is_wp_error($b))return$b;$items=array();foreach((array)($b['items']??array())as$d)$items[]=array_intersect_key($d,array_flip(array('public_id','display_name','professional_title','specialty','country','city','languages','consultation_modes','profile_url','clinic_url','appointment_url','verified_at')));$res=rest_ensure_response(array('items'=>$items,'offline_copy'=>true,'stale_label_required'=>true,'generated_at'=>gmdate('c'),'expires_at'=>gmdate('c',time()+6*HOUR_IN_SECONDS)));$res->header('Cache-Control','public, max-age=21600, stale-if-error=86400');return$res;}
}
