<?php
defined( 'ABSPATH' ) || exit;

trait DDD_Admin_Trait_2 {
	public function directory() {
		$this->guard( 'ddd_manage_directory' );
		global $wpdb;
		$table = DDD_Repository::table( 'projection' );
		$page = isset( $_GET['ddd_page'] ) ? max( 1, absint( $_GET['ddd_page'] ) ) : 1;
		$offset = ( $page - 1 ) * self::PER_PAGE;
		$total = (int) $wpdb->get_var( "SELECT COUNT(*) FROM {$table}" ); // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		$rows = $wpdb->get_results( $wpdb->prepare( "SELECT * FROM {$table} ORDER BY eligible DESC, featured DESC, updated_at DESC, doctor_id ASC LIMIT %d OFFSET %d", self::PER_PAGE, $offset ), ARRAY_A ); // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		?>
		<div class="wrap ddd-admin"><h1><?php esc_html_e( 'Doctors Directory Records', DDD_TEXT_DOMAIN ); ?></h1><p><?php esc_html_e( 'File 07 owns only the public projection, search, feature state and moderation records. Identity, verification, profiles and clinics remain with their canonical modules.', DDD_TEXT_DOMAIN ); ?></p>
		<div class="ddd-admin-actions"><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><input type="hidden" name="action" value="ddd_run_reconciliation"><?php wp_nonce_field( 'ddd_run_reconciliation' ); ?><input type="hidden" name="cursor" value="0"><button class="button button-primary" type="submit"><?php esc_html_e( 'Run bounded reconciliation', DDD_TEXT_DOMAIN ); ?></button></form></div>
		<table class="widefat striped"><thead><tr><th><?php esc_html_e( 'Doctor', DDD_TEXT_DOMAIN ); ?></th><th><?php esc_html_e( 'Eligibility', DDD_TEXT_DOMAIN ); ?></th><th><?php esc_html_e( 'Projection', DDD_TEXT_DOMAIN ); ?></th><th><?php esc_html_e( 'Feature state', DDD_TEXT_DOMAIN ); ?></th><th><?php esc_html_e( 'Actions', DDD_TEXT_DOMAIN ); ?></th></tr></thead><tbody>
		<?php if ( $rows ) : foreach ( $rows as $row ) : $reasons = (array) json_decode( $row['reasons_json'], true ); ?>
		<tr><td><strong><?php echo esc_html( $row['display_name'] ? $row['display_name'] : sprintf( __( 'Doctor #%d', DDD_TEXT_DOMAIN ), $row['doctor_id'] ) ); ?></strong><br><code><?php echo esc_html( $row['public_id'] ); ?></code><br><small><?php echo esc_html( trim( $row['city'] . ', ' . $row['country'], ', ' ) ); ?></small></td>
		<td><strong><?php echo esc_html( $row['eligible'] ? __( 'Eligible', DDD_TEXT_DOMAIN ) : __( 'Not eligible', DDD_TEXT_DOMAIN ) ); ?></strong><br><small><?php echo esc_html( $reasons ? implode( ', ', $reasons ) : __( 'No blockers', DDD_TEXT_DOMAIN ) ); ?></small></td>
		<td><?php echo esc_html( sprintf( __( 'Version %1$d · %2$d%% complete', DDD_TEXT_DOMAIN ), $row['version'], $row['completeness'] ) ); ?><br><small><?php echo esc_html( $row['updated_at'] ); ?> UTC</small></td>
		<td><?php echo esc_html( $row['featured'] ? ( $row['feature_label'] ? $row['feature_label'] : __( 'Featured', DDD_TEXT_DOMAIN ) ) : __( 'Not featured', DDD_TEXT_DOMAIN ) ); ?><br><small><?php echo esc_html( $row['feature_end'] ? sprintf( __( 'Expires %s UTC', DDD_TEXT_DOMAIN ), $row['feature_end'] ) : '' ); ?></small></td>
		<td><form class="ddd-admin-form" method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><input type="hidden" name="action" value="ddd_rebuild_doctor"><input type="hidden" name="doctor_id" value="<?php echo absint( $row['doctor_id'] ); ?>"><input type="hidden" name="expected_version" value="<?php echo absint( $row['version'] ); ?>"><?php wp_nonce_field( 'ddd_rebuild_doctor_' . $row['doctor_id'] ); ?><button class="button" type="submit"><?php esc_html_e( 'Reconcile now', DDD_TEXT_DOMAIN ); ?></button></form>
		<?php if ( current_user_can( 'ddd_manage_features' ) && $row['eligible'] ) : ?><details><summary><?php esc_html_e( 'Feature controls', DDD_TEXT_DOMAIN ); ?></summary><form class="ddd-admin-form" method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><input type="hidden" name="action" value="ddd_feature_doctor"><input type="hidden" name="doctor_id" value="<?php echo absint( $row['doctor_id'] ); ?>"><input type="hidden" name="expected_version" value="<?php echo absint( $row['version'] ); ?>"><?php wp_nonce_field( 'ddd_feature_doctor_' . $row['doctor_id'] ); ?><label><input type="checkbox" name="enabled" value="1" <?php checked( $row['featured'], 1 ); ?>> <?php esc_html_e( 'Featured', DDD_TEXT_DOMAIN ); ?></label><label><?php esc_html_e( 'Public label', DDD_TEXT_DOMAIN ); ?><input name="label" maxlength="120" value="<?php echo esc_attr( $row['feature_label'] ); ?>"></label><label><?php esc_html_e( 'Start UTC', DDD_TEXT_DOMAIN ); ?><input type="datetime-local" name="start" value="<?php echo esc_attr( $row['feature_start'] ? gmdate( 'Y-m-d\TH:i', strtotime( $row['feature_start'] . ' UTC' ) ) : '' ); ?>"></label><label><?php esc_html_e( 'Expiry UTC', DDD_TEXT_DOMAIN ); ?><input type="datetime-local" name="end" value="<?php echo esc_attr( $row['feature_end'] ? gmdate( 'Y-m-d\TH:i', strtotime( $row['feature_end'] . ' UTC' ) ) : '' ); ?>"></label><label><?php esc_html_e( 'Required reason', DDD_TEXT_DOMAIN ); ?><textarea name="reason" maxlength="1000" required><?php echo esc_textarea( $row['feature_reason'] ); ?></textarea></label><button class="button button-primary" type="submit"><?php esc_html_e( 'Save feature state', DDD_TEXT_DOMAIN ); ?></button></form></details><?php endif; ?></td></tr>
		<?php endforeach; else : ?><tr><td colspan="5"><?php esc_html_e( 'No directory projections exist yet. Run reconciliation.', DDD_TEXT_DOMAIN ); ?></td></tr><?php endif; ?>
		</tbody></table><?php echo $this->pagination( $page, $total, self::PER_PAGE, 'ddd_page', 'ddd-directory' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></div>
		<?php
	}
}
